"""
voice.py — SQLAlchemy ORM models for the VOICE side (Pipeline A) tables.

These map the REAL voice tables defined in db/schema.sql (care_recipients,
service_locations, staff_shift_assignments, support_plan_goals,
prescribed_medications) — NOT the clerk-side read-models in db/models/pipeline_a.py,
which describe a different schema.

SCOPE
Covers the tables/columns that the read path (load_roster, load_context) needs.
Each class maps one table; __tablename__ must match schema.sql. Only the columns
the code actually reads are mapped — add more as the rest of db_context.py migrates.
"""

import uuid
from datetime import date, datetime, time

from sqlalchemy import ARRAY, Boolean, Date, DateTime, ForeignKey, Text, Time, text
from sqlalchemy.dialects.postgresql import JSONB, UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column

from db.voice_session import VoiceBase


class CareRecipient(VoiceBase):
    """care_recipients — the individual receiving support."""
    __tablename__ = "care_recipients"

    care_recipient_id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True)
    full_name: Mapped[str] = mapped_column(Text)
    medicaid_id: Mapped[str] = mapped_column(Text)
    date_of_birth: Mapped[date] = mapped_column(Date)
    waiver_program: Mapped[str] = mapped_column(Text)
    primary_diagnosis_code: Mapped[str] = mapped_column(Text)


class ServiceLocation(VoiceBase):
    """service_locations — where the shift happens. (Partial mapping.)"""
    __tablename__ = "service_locations"

    location_id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True)
    service_location_name: Mapped[str] = mapped_column(Text)


class StaffShiftAssignment(VoiceBase):
    """staff_shift_assignments — the DSP→recipient assignment for a given day.

    The "hub" table the read path starts from: it carries the FKs to the
    recipient and the location, plus the schedule, the DSP's name, and the
    billing code.
    """
    __tablename__ = "staff_shift_assignments"

    shift_assignment_id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True)
    care_recipient_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey("care_recipients.care_recipient_id")
    )
    location_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey("service_locations.location_id")
    )
    direct_support_professional_name: Mapped[str] = mapped_column(Text)
    shift_date: Mapped[date] = mapped_column(Date)
    scheduled_start_time: Mapped[time] = mapped_column(Time)
    scheduled_end_time: Mapped[time] = mapped_column(Time)
    service_billing_code: Mapped[str] = mapped_column(Text)


class SupportPlanGoal(VoiceBase):
    """support_plan_goals — one active/inactive ISP goal for a recipient."""
    __tablename__ = "support_plan_goals"

    goal_id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True)
    care_recipient_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey("care_recipients.care_recipient_id")
    )
    goal_category: Mapped[str] = mapped_column(Text)
    goal_description: Mapped[str] = mapped_column(Text)
    is_currently_active: Mapped[bool] = mapped_column(Boolean)


class PrescribedMedication(VoiceBase):
    """prescribed_medications — one prescribed med (with its scheduled time)."""
    __tablename__ = "prescribed_medications"

    medication_id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True)
    care_recipient_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey("care_recipients.care_recipient_id")
    )
    medication_name: Mapped[str] = mapped_column(Text)
    dosage_amount: Mapped[str] = mapped_column(Text)
    administration_route: Mapped[str] = mapped_column(Text)
    scheduled_time_of_day: Mapped[time] = mapped_column(Time)
    is_currently_active: Mapped[bool] = mapped_column(Boolean)


# --- Write-path models (the submit/atomic-write tables) -----------------------

class DocumentedCareSession(VoiceBase):
    """documented_care_sessions — one submitted progress note.

    Only the columns the write path sets are mapped. The array/jsonb columns are
    given real SQLAlchemy types so callers pass plain Python lists/dicts — no
    manual ::uuid[] cast or psycopg2 Json() wrapper needed. care_session_id is
    generated by the DB (uuid_generate_v4) and returned on insert.
    """
    __tablename__ = "documented_care_sessions"

    care_session_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), primary_key=True, server_default=text("uuid_generate_v4()")
    )
    shift_assignment_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey("staff_shift_assignments.shift_assignment_id")
    )
    care_recipient_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey("care_recipients.care_recipient_id")
    )
    care_session_narrative: Mapped[str | None] = mapped_column(Text)
    activities_performed: Mapped[list[str]] = mapped_column(ARRAY(Text))
    level_of_support_provided: Mapped[str | None] = mapped_column(Text)
    recipient_engagement_notes: Mapped[str | None] = mapped_column(Text)
    health_observations_notes: Mapped[str | None] = mapped_column(Text)
    behavioral_observations_notes: Mapped[str | None] = mapped_column(Text)
    community_outing_notes: Mapped[str | None] = mapped_column(Text)
    meals_provided: Mapped[list[str]] = mapped_column(ARRAY(Text))
    personal_care_activities: Mapped[list[str]] = mapped_column(ARRAY(Text))
    goals_addressed_in_session: Mapped[list[uuid.UUID]] = mapped_column(ARRAY(PGUUID(as_uuid=True)))
    goals_resolution: Mapped[list[dict]] = mapped_column(JSONB)
    documentation_gap_flags: Mapped[list[str]] = mapped_column(ARRAY(Text))
    ai_confidence_rating: Mapped[str | None] = mapped_column(Text)
    dsp_has_signed: Mapped[bool] = mapped_column(Boolean)
    session_status: Mapped[str] = mapped_column(Text)


class MedicationAdministrationRecord(VoiceBase):
    """medication_administration_records — one administered/withheld dose,
    tied to a care session. administration_record_id is DB-generated."""
    __tablename__ = "medication_administration_records"

    administration_record_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), primary_key=True, server_default=text("uuid_generate_v4()")
    )
    care_session_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey("documented_care_sessions.care_session_id")
    )
    medication_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey("prescribed_medications.medication_id")
    )
    was_medication_given: Mapped[bool] = mapped_column(Boolean)
    actual_administration_time: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    reason_if_not_given: Mapped[str | None] = mapped_column(Text)
